### ISSUE TITLE
add a software license?

### ISSUE THREAD

**Issue by junipertcy** [kansuke231/NetworkClassification#1]
Hi @kansuke231,

Thank you for having the code for your MS thesis and [this paper](https://arxiv.org/abs/1710.11304) open sourced. While it is very useful for my research, I found that it lacks a proper software license. The users cannot redistribute the software appropriately without conforming to the rules. Would you please add one when you have a moment? Possibly choose one via the instructions from [this website](https://choosealicense.com/). Big thanks.

-tc

**Comment by kansuke231** [comment]
Hi @junipertcy 
Thanks for the comments! I added the MIT License to this repository.
If you have any issue with the code, please let me know.

Kansuke
